### ISSUE TITLE
plugin does not load

### ISSUE THREAD

**Issue by Zarkness2** [aglerr/IslandNPC#2]
Hi, when I put your original plugin-islandnpc.jar in the plugins folder and start the server I get that error and the plugin does not load, could you fix it?

![image](https://user-images.githubusercontent.com/48263644/167252991-d29ab401-0533-4df2-87eb-9838f1ce6b69.png)

**Comment by Zarkness2** [comment]
@mdaffa48 hi?

**Comment by mdaffa48** [comment]
Hello @Zarkness thanks for reporting this issue, I haven't been able to maintain this plugin due to IRL stuff. However, I'm going to remember this issue and will fix it at some point in the future.

**Comment by Zarkness2** [comment]
ok and I hope the problems you had IRL were not serious, I hope you can fix it soon because I would like to use it on my server.

**Comment by Zarkness2** [comment]
by the way @mdaffa48  do you have a discord group?

**Comment by mdaffa48** [comment]
> by the way @mdaffa48 do you have a discord group?

I actually have a discord server, you can join here at https://discord.muhammaddaffa.com

**Comment by Zarkness2** [comment]
thanks

**Comment by Zarkness2** [comment]
Hello, is there any news about the plugin? I would love to use it on my server but there is no other that is almost finished and working only this one, when do you think it could be fixed the bug? @mdaffa48

**Comment by mdaffa48** [comment]
@Zarkness I've updated a bunch of libraries that the plugin use. You can find the jar on the releases tab https://github.com/mdaffa48/IslandNPC/releases/tag/1.0 and let me know If you found any issues.

**Comment by Zarkness2** [comment]
ok and thank you very much, now I will try the plugin

**Comment by Zarkness2** [comment]
@mdaffa48 hello, i just tried your plugin with the default superiorskyblock config and with your default plugin config and when i put the /islandnpc reset player command it gives the first error shown in the link and when i put the /islandnpc movenpc player command it gives me the egg but when i click to put it i get the second error message
https://paste.helpch.at/ojiyocegiw.sql

**Comment by Zarkness2** [comment]
another thing i am seeing that the npcs data is saved in a .yml could you add database support to avoid any data loss?

**Comment by Zarkness2** [comment]
hope you can fix that little bug soon @mdaffa48

**Comment by Zarkness2** [comment]
Hello? @mdaffa48 sorry for the mentions

**Comment by Zarkness2** [comment]
ideas that I can think of that could be added plus some bugs that happen and could be fixed

feature:
add a line in the config which is to choose the name of the npc and not as it is now.
add support for hologram plugins such as decenthologram, so that this plugin can handle the hologram issue
fix the /islandnpc movenpc command so that when your inventory is full it sends you a message saying Your inventory is full!
add a message that you have placed the npc
add a message saying &cYou can''t place it here!
add a message saying that you must place it on your island
add the possibility to add aliases to the commands
fix that every time you give islandnpc reload and move the npc where it was before the npc stays a hologram with the name of the npc this I didn't test it when restarting the server

the config that I thought of could be as it appears in the file, since it is a little better organized.

a note about the decenthologram dev gave an announcement recently saying that he was going to recode it completely but he didn't say when he was going to start or how long it would take.

https://paste.helpch.at/josequgeze.coffeescript @mdaffa48

**Comment by Zarkness** [comment]
@mdaffa48

**Comment by Zarkness** [comment]
@mdaffa48

**Comment by Zarkness** [comment]
hi @mdaffa48 ?

**Comment by Zarkness** [comment]
@mdaffa48

**Comment by Zarkness** [comment]
@mdaffa48 ?

**Comment by Zarkness** [comment]
@mdaffa48

**Comment by Zarkness** [comment]
@mdaffa48

**Comment by Zarkness2** [comment]
hi @mdaffa48
